apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tomcat
  namespace: monitor
  labels:
    app: tomcat
    team: dev
    release: mdsp-monitor
spec:
  selector:
    matchLabels:
      app: tomcat
  endpoints:
    - port: web123
      interval: 10s
  namespaceSelector:
    any: true