server:
  port: 8080
spring:
  application:
    name: springboot2.1.x
management:
  endpoints:
    web:
      base-path: /actuator # 2.x 默认为 /actuator
      exposure:
        include: 'prometheus'
    jmx:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}